### ISSUE TITLE
Bump postcard dependency to 1.0.0

### ISSUE THREAD

**Issue by PhotonQuantum** [caio/foca#8]
Postcard 1.0.0 fixed an issue which caused chrono types and `#[serde_as(as = "DisplayFromStr")]` failed to be serialized. See https://github.com/jamesmunns/postcard/issues/32.

In my use case, I put `http::Uri` type into my identity type, which doesn't implement serde traits. So I used `DisplayFromStr` to work it around. However, postcard codec failed to serialize it due to the issue stated above.

**Comment by caio** [comment]
Thanks a lot for the report!

Would you like to submit a pull request for this? Otherwise I'll tentatively bump and release a new version this weekend

**Comment by caio** [comment]
I've just [released v0.4.0](https://github.com/caio/foca/releases/tag/v0.4.0) with your contribution. Closing the issue.

Thanks again!
